# Generated by Django 3.2.9 on 2023-02-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='store/img/')),
            ],
        ),
    ]
